from django.db import models
from django_countries.fields import CountryField
leagues = (
    ("premier league", "Premier League"),
    ("championship", "Championship"),
    ("league 1", "League 1"),
    ("epl league 1", "EPL League 1"),
    ("epl league 2", "EPL League 2"),
    ("laliga", "LaLiga"),
    ("Serie A", "Serie A"),
    ("Serie B", "Serie B"),
    ("Bundesliga", "Bundesliga"),
    ("Ligue 1", "Ligue 1"),
    ("Ligue 2", "Ligue 2"),
    ("Primeira Liga", "Primeira Liga"),
    ("Eredivisie", "Eredivisie"),
    ("Brasileirão Série A", "Brasileirão Série A"),
    ("Brasileirão Série B", "Brasileirão Série B"),
    ("MLS", "MLS"),
    ("Argentine Primera División", "Argentine Primera División"),
    ("Scottish Premiership", "Scottish Premiership"),
    ("Belgian Pro League", "Belgian Pro League"),
    ("Turkish Süper Lig", "Turkish Süper Lig"),
    ("Russian Premier League", "Russian Premier League"),
    ("Greek Super League", "Greek Super League"),
    ("Swiss Super League", "Swiss Super League"),
    ("Austrian Bundesliga", "Austrian Bundesliga"),
    ("Danish Superliga", "Danish Superliga"),
    ("Norwegian Eliteserien", "Norwegian Eliteserien"),
    ("Swedish Allsvenskan", "Swedish Allsvenskan"),
    ("Chinese Super League", "Chinese Super League"),
    ("J1 League", "J1 League"),
    ("K League 1", "K League 1"),
    ("Australian A-League", "Australian A-League"),
    ("Mexican Liga MX", "Mexican Liga MX"),
    ("Saudi Pro League", "Saudi Pro League"),
    ("UAE Pro League", "UAE Pro League"),
    ("Qatar Stars League", "Qatar Stars League"),
    ("Indian Super League", "Indian Super League"),
    ("South African Premier Division", "South African Premier Division"),
    ("Egyptian Premier League", "Egyptian Premier League"),
    ("Moroccan Botola Pro", "Moroccan Botola Pro"),
    ("Tunisian Ligue Professionnelle 1", "Tunisian Ligue Professionnelle 1"),
    ("Algerian Ligue Professionnelle 1", "Algerian Ligue Professionnelle 1"),
    ("Nigerian Professional Football League", "Nigerian Professional Football League"),
    ("Ghana Premier League", "Ghana Premier League"),
    ("Kenyan Premier League", "Kenyan Premier League"),
    ("Zambian Super League", "Zambian Super League"),
    ("Uruguayan Primera División", "Uruguayan Primera División"),
    ("Paraguayan Primera División", "Paraguayan Primera División"),
    ("Chilean Primera División", "Chilean Primera División"),
    ("Peruvian Primera División", "Peruvian Primera División"),
    ("Bolivian Primera División", "Bolivian Primera División"),
    ("Colombian Categoría Primera A", "Colombian Categoría Primera A"),
    ("Venezuelan Primera División", "Venezuelan Primera División"),
    ("Costa Rican Primera División", "Costa Rican Primera División"),
    ("Honduran Liga Nacional", "Honduran Liga Nacional"),
    ("Guatemalan Liga Nacional", "Guatemalan Liga Nacional"),
    ("Salvadoran Primera División", "Salvadoran Primera División"),
    ("Panamanian Liga Panameña de Fútbol", "Panamanian Liga Panameña de Fútbol"),
    ("Nicaraguan Primera División", "Nicaraguan Primera División"),
    ("Jamaican National Premier League", "Jamaican National Premier League"),
    ("Trinidad and Tobago Pro League", "Trinidad and Tobago Pro League"),
    ("Haitian Ligue Haïtienne", "Haitian Ligue Haïtienne"),
    ("Cuban Campeonato Nacional", "Cuban Campeonato Nacional"),
    ("Puerto Rican Liga Puerto Rico", "Puerto Rican Liga Puerto Rico"),
    ("Dominican Liga Dominicana de Fútbol", "Dominican Liga Dominicana de Fútbol"),
    ("Canadian Premier League", "Canadian Premier League"),
    ("Icelandic Úrvalsdeild", "Icelandic Úrvalsdeild"),
    ("Finnish Veikkausliiga", "Finnish Veikkausliiga"),
    ("Irish Premier Division", "Irish Premier Division"),
    ("Welsh Premier League", "Welsh Premier League"),
    ("Northern Irish Premiership", "Northern Irish Premiership"),
    ("Luxembourg National Division", "Luxembourg National Division"),
    ("Maltese Premier League", "Maltese Premier League"),
    ("Cypriot First Division", "Cypriot First Division"),
    ("Israeli Premier League", "Israeli Premier League"),
    ("Jordanian Pro League", "Jordanian Pro League"),
    ("Lebanese Premier League", "Lebanese Premier League"),
    ("Iraqi Premier League", "Iraqi Premier League"),
    ("Syrian Premier League", "Syrian Premier League"),
    ("Kuwaiti Premier League", "Kuwaiti Premier League"),
    ("Bahraini Premier League", "Bahraini Premier League"),
    ("Omani Professional League", "Omani Professional League"),
    ("Yemeni League", "Yemeni League"),
    ("Bangladeshi Premier League", "Bangladeshi Premier League"),
    ("Pakistani Premier League", "Pakistani Premier League"),
    ("Sri Lankan Premier League", "Sri Lankan Premier League"),
    ("Nepalese A-Division League", "Nepalese A-Division League"),
    ("Maldivian Dhivehi Premier League", "Maldivian Dhivehi Premier League"),
    ("Bhutan National League", "Bhutan National League"),
    ("Afghan Premier League", "Afghan Premier League"),
    ("Uzbekistan Super League", "Uzbekistan Super League"),
    ("Kazakhstan Premier League", "Kazakhstan Premier League"),
    ("Kyrgyzstan League", "Kyrgyzstan League"),
    ("Tajikistan Higher League", "Tajikistan Higher League"),
    ("Turkmenistan Ýokary Liga", "Turkmenistan Ýokary Liga"),
    ("Mongolian Premier League", "Mongolian Premier League"),
    ("Vietnamese V.League 1", "Vietnamese V.League 1"),
    ("Thai League 1", "Thai League 1"),
    ("Malaysian Super League", "Malaysian Super League"),
    ("Singapore Premier League", "Singapore Premier League"),
    ("Indonesian Liga 1", "Indonesian Liga 1"),
    ("Philippines Football League", "Philippines Football League"),
    ("Myanmar National League", "Myanmar National League"),
    ("Cambodian League", "Cambodian League"),
    ("Laos Premier League", "Laos Premier League"),
    ("Brunei Super League", "Brunei Super League"),
    ("Timor-Leste Primeira Divisão", "Timor-Leste Primeira Divisão"),
    ("Hong Kong Premier League", "Hong Kong Premier League"),
    ("Macau Liga de Elite", "Macau Liga de Elite"),
    ("Taiwan Football Premier League", "Taiwan Football Premier League"),
    ("North Korean Premier League", "North Korean Premier League"),
    ("New Zealand Football Championship", "New Zealand Football Championship"),
    ("Fijian National Football League", "Fijian National Football League"),
    ("Papua New Guinea National Soccer League", "Papua New Guinea National Soccer League"),
    ("Solomon Islands S-League", "Solomon Islands S-League"),
    ("Vanuatu Premia Divisen", "Vanuatu Premia Divisen"),
    ("New Caledonia Super Ligue", "New Caledonia Super Ligue"),
    ("Tahiti Ligue 1", "Tahiti Ligue 1"),
    ("Samoa National League", "Samoa National League"),
    ("Tonga Major League", "Tonga Major League"),
    ("Cook Islands Round Cup", "Cook Islands Round Cup"),
    ("American Samoa FFAS Senior League", "American Samoa FFAS Senior League"),
    ("Guam Soccer League", "Guam Soccer League"),
    ("Northern Mariana Islands M*League", "Northern Mariana Islands M*League"),
    ("Micronesia Football League", "Micronesia Football League"),
    ("Palau Soccer League", "Palau Soccer League")
)
# Create your models here.
class Fixture(models.Model):
    home_team = models.CharField(max_length=100)
    away_team = models.CharField(max_length=100)
    date = models.DateTimeField()
    time= models.TimeField(default='00:00:00')
    created_at= models.DateTimeField(auto_now=True)
    prediction= models.CharField(max_length=100,null=True,blank=True)
    result_home_team_score= models.IntegerField(null=True,blank=True)
    result_away_team_score= models.IntegerField(null=True,blank=True)
    league =models.CharField(choices=leagues,max_length=100)
    odds = models.DecimalField(blank=True,null=True,max_digits=5,decimal_places=2)
    country = CountryField()
    season = models.CharField(max_length=100)
    confidence= models.IntegerField(default=50)

    def __str__(self):
        return f"{self.home_team} vs {self.away_team} on {self.date} in {self.league} season {self.season} in {self.country}"